name: DevOps Workflow

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v1
        with:
          java-version: 20

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

  merge_main:
    needs: run_tests
    runs-on: ubuntu-latest
    if: success()  # 只有在 run_tests 成功后才运行

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Merge main branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git pull origin main
          git merge main
          git push origin main
